config/routes.rb
Rails.application.routes.draw do

  resources :knows

  resources :comentarios

  resources :subcategorias

  resources :categorias
  
  get 'tickets/abiertas' => 'tickets#abiertas'
  post 'tickets/asignar' => 'tickets#asignar'
  resources :tickets

  resources :subcategoria

  resources :categoria

  resources :usuarios

  resources :empleados

  resources :areas

  resources :empresas

  resources :roles
  
  

   root 'usuarios#login'

  
  match 'auth/:provider/callback', to: 'sessions#create', :via => [:get, :post]
  match 'auth/failure', to: redirect('/'), :via => [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', :via => [:get, :post]
end

app/models/area.rb
class Area < ActiveRecord::Base
  belongs_to :empresa
  has_many :categoria
  has_many :empleados
  has_many :ticket
  has_many :know
end

app/models/categoria.rb
class Categoria < ActiveRecord::Base
  belongs_to :area
  has_many :subcategoria
  has_many :ticket
  has_many :know
end

app/models/comentario.rb
class Comentario < ActiveRecord::Base
  belongs_to :ticket
  belongs_to :empleado
  belongs_to :usuario
end

app/models/empleado.rb
class Empleado < ActiveRecord::Base
  belongs_to :empresa
  belongs_to :area
  belongs_to :role
  has_many :comentario
end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
	has_many :area
	has_many :usuario
	has_many :empleado
	has_many :ticket
end

app/models/know.rb
class Know < ActiveRecord::Base
  belongs_to :area
  belongs_to :categoria
  belongs_to :subcategoria
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_many :empleado
	has_many :usuario
end

app/models/subcategoria.rb
class Subcategoria < ActiveRecord::Base
  belongs_to :categoria
  has_many :ticket
  has_many :know
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  has_many :comentario
  accepts_nested_attributes_for :comentario, allow_destroy: true
    
  belongs_to :empresa
  belongs_to :usuario
  belongs_to :empleado
  belongs_to :categoria
  belongs_to :subcategoria
  belongs_to :area
  
  
end

app/models/user.rb
class User < ActiveRecord::Base
    def self.from_omniauth(auth)
      where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.name = auth.info.name
        user.oauth_token = auth.credentials.token
        user.oauth_expires_at = Time.at(auth.credentials.expires_at)
        user.save!
      end
    end
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  belongs_to :empresa
  belongs_to :role
  has_many :ticket
  has_many :comentario
end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
  before_action :set_comentario, only: [:show, :edit, :update, :destroy]

  # GET /comentarios
  # GET /comentarios.json
  def index
    @comentarios = Comentario.all
    @menu = "menu1"
  end

  # GET /comentarios/1
  # GET /comentarios/1.json
  def show
    @menu = "menu1"
  end

  # GET /comentarios/new
  def new
    @comentario = Comentario.new
  end

  # GET /comentarios/1/edit
  def edit
    @menu = "menu1"
  end

  # POST /comentarios
  # POST /comentarios.json
  def create
    @comentario = Comentario.new(comentario_params)

    respond_to do |format|
      if @comentario.save
        format.html { redirect_to @comentario, notice: 'Comentario was successfully created.' }
        format.json { render :show, status: :created, location: @comentario }
      else
        format.html { render :new }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comentarios/1
  # PATCH/PUT /comentarios/1.json
  def update
    respond_to do |format|
      if @comentario.update(comentario_params)
        format.html { redirect_to @comentario, notice: 'Comentario was successfully updated.' }
        format.json { render :show, status: :ok, location: @comentario }
      else
        format.html { render :edit }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comentarios/1
  # DELETE /comentarios/1.json
  def destroy
    @comentario.destroy
    respond_to do |format|
      format.html { redirect_to comentarios_url, notice: 'Comentario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comentario
      @comentario = Comentario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comentario_params
      params.require(:comentario).permit(:comentario, :ticket_id, :empleado_id, :usuario_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/categoria_helper.rb
module CategoriaHelper
end

app/helpers/categorias_helper.rb
module CategoriasHelper
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/helpers/empleados_helper.rb
module EmpleadosHelper
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/helpers/knows_helper.rb
module KnowsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
    
    def estado(id)
        case id
        when 1
            "Abierto"
        when 2
            "En proceso"
        when 3
            "Atendido"
        else
            "Error"
        end
    end
    
    def prioridad(id)
        case id
        when 1
            "Baja"
        when 2
            "Normal"
        when 3
            "Alta"
        else
            ""
        end
    end
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/comentarios/_form.html.erb
<%= simple_form_for(@comentario) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :comentario %>
    <%= f.association :ticket %>
    <%= f.association :empleado %>
    <%= f.association :usuario %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/comentarios/edit.html.erb
<h1>Editing Comentario</h1>

<%= render 'form' %>

<%= link_to 'Show', @comentario %> |
<%= link_to 'Back', comentarios_path %>

app/views/comentarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comentarios</h1>

<table>
  <thead>
    <tr>
      <th>Comentario</th>
      <th>Ticket</th>
      <th>Empleado</th>
      <th>Usuario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comentarios.each do |comentario| %>
      <tr>
        <td><%= comentario.comentario %></td>
        <td><%= comentario.ticket %></td>
        <td><%= comentario.empleado %></td>
        <td><%= comentario.usuario %></td>
        <td><%= link_to 'Show', comentario %></td>
        <td><%= link_to 'Edit', edit_comentario_path(comentario) %></td>
        <td><%= link_to 'Destroy', comentario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comentario', new_comentario_path %>

app/views/comentarios/new.html.erb
<h1>New Comentario</h1>

<%= render 'form' %>

<%= link_to 'Back', comentarios_path %>

app/views/comentarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Comentario:</strong>
  <%= @comentario.comentario %>
</p>

<p>
  <strong>Ticket:</strong>
  <%= debug(@comentario.ticket) %>
</p>

<p>
  <strong>Empleado:</strong>
  <%= debug(@comentario.empleado) %>
</p>

<p>
  <strong>Usuario:</strong>
  <%= debug(@comentario.usuario) %>
</p>

<%= link_to 'Edit', edit_comentario_path(@comentario) %> |
<%= link_to 'Back', comentarios_path %>