config/routes.rb
Rails.application.routes.draw do

  resources :knows

  resources :comentarios

  resources :subcategorias

  resources :categorias
  
  get 'tickets/abiertas' => 'tickets#abiertas'
  post 'tickets/asignar' => 'tickets#asignar'
  resources :tickets

  resources :subcategoria

  resources :categoria

  resources :usuarios

  resources :empleados

  resources :areas

  resources :empresas

  resources :roles
  
  

   root 'usuarios#login'

  
  match 'auth/:provider/callback', to: 'sessions#create', :via => [:get, :post]
  match 'auth/failure', to: redirect('/'), :via => [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', :via => [:get, :post]
end

app/models/area.rb
class Area < ActiveRecord::Base
  belongs_to :empresa
  has_many :categoria
  has_many :empleados
  has_many :ticket
  has_many :know
end

app/models/categoria.rb
class Categoria < ActiveRecord::Base
  belongs_to :area
  has_many :subcategoria
  has_many :ticket
  has_many :know
end

app/models/comentario.rb
class Comentario < ActiveRecord::Base
  belongs_to :ticket
  belongs_to :empleado
  belongs_to :usuario
end

app/models/empleado.rb
class Empleado < ActiveRecord::Base
  belongs_to :empresa
  belongs_to :area
  belongs_to :role
  has_many :comentario
end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
	has_many :area
	has_many :usuario
	has_many :empleado
	has_many :ticket
end

app/models/know.rb
class Know < ActiveRecord::Base
  belongs_to :area
  belongs_to :categoria
  belongs_to :subcategoria
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_many :empleado
	has_many :usuario
end

app/models/subcategoria.rb
class Subcategoria < ActiveRecord::Base
  belongs_to :categoria
  has_many :ticket
  has_many :know
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  has_many :comentario
  accepts_nested_attributes_for :comentario, allow_destroy: true
    
  belongs_to :empresa
  belongs_to :usuario
  belongs_to :empleado
  belongs_to :categoria
  belongs_to :subcategoria
  belongs_to :area
  
  
end

app/models/user.rb
class User < ActiveRecord::Base
    def self.from_omniauth(auth)
      where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.name = auth.info.name
        user.oauth_token = auth.credentials.token
        user.oauth_expires_at = Time.at(auth.credentials.expires_at)
        user.save!
      end
    end
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  belongs_to :empresa
  belongs_to :role
  has_many :ticket
  has_many :comentario
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :set_area, only: [:show, :edit, :update, :destroy]

  # GET /areas
  # GET /areas.json
  def index
    @areas = Area.all
    @menu = "menu2"
  end

  # GET /areas/1
  # GET /areas/1.json
  def show
    @menu = "menu2"  
  end

  # GET /areas/new
  def new
    @area = Area.new
    @empleados = Empleado.where(:role_id => 2)
    
    #Users.where(:name => "Test_name").limit(10)
    
    @menu = "menu2"
  end

  # GET /areas/1/edit
  def edit
    @menu = "menu2"
  end

  # POST /areas
  # POST /areas.json
  def create
    @area = Area.new(area_params)

    respond_to do |format|
      if @area.save
        format.html { redirect_to @area, notice: 'Area creada satisfactoriamente' }
        format.json { render :show, status: :created, location: @area }
      else
        format.html { render :new }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /areas/1
  # PATCH/PUT /areas/1.json
  def update
    respond_to do |format|
      if @area.update(area_params)
        format.html { redirect_to @area, notice: 'Area actualizada satisfactoriamente' }
        format.json { render :show, status: :ok, location: @area }
      else
        format.html { render :edit }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /areas/1
  # DELETE /areas/1.json
  def destroy
    @area.destroy
    respond_to do |format|
      format.html { redirect_to areas_url, notice: 'Area eliminada satisfactoriamente' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_area
      @area = Area.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def area_params
      params.require(:area).permit(:name, :empresa_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/categoria_helper.rb
module CategoriaHelper
end

app/helpers/categorias_helper.rb
module CategoriasHelper
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/helpers/empleados_helper.rb
module EmpleadosHelper
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/helpers/knows_helper.rb
module KnowsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
    
    def estado(id)
        case id
        when 1
            "Abierto"
        when 2
            "En proceso"
        when 3
            "Atendido"
        else
            "Error"
        end
    end
    
    def prioridad(id)
        case id
        when 1
            "Baja"
        when 2
            "Normal"
        when 3
            "Alta"
        else
            ""
        end
    end
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/areas/_form.html.erb
<%= simple_form_for @area, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name, :label => "Unidad de Negocio" %>
  
  <%#= f.label :empresa_id, "Empleado" %>
  <%#= f.collection_select :empleado_id, @empleados, :id, :apellidos , {prompt: "Seleccione Empleado"}, {class: "form-control"} %>
  <%#= error_span(@area[:empleado_id]) %>

  <div class="form-group">
  <%#= f.label :empresa_id %>
  <%#= f.collection_select :empresa_id, Empresa.all, :id, :name, {prompt: "Select a Empresa"}, {class: "form-control"} %>
  <%#= error_span(@area[:empresa_id]) %>
  </div>

    <%= f.submit 'Grabar', :class => 'btn btn-sm btn-primary' %>    
    <%= link_to 'Atrás', areas_path, :class => 'btn btn-sm btn-default' %>
<% end %>

app/views/areas/edit.html.erb
<%- model_class = Area -%>
<div class="page-header">
  <h1>Editar Unidad de Negocio</h1>
</div>
<%= render :partial => 'form' %>

app/views/areas/index.html.erb
<%- model_class = Area -%>
<div class="page-header">
  <h1>Unidad de Negocio</h1>
</div>
<table class="table table-striped">
  
    <!--<tr>
      <th><%#= model_class.human_attribute_name(:id) %></th>
      <th><%#= model_class.human_attribute_name(:name) %></th>
      <th><%#=t '.actions', :default => t("helpers.actions") %></th>
    </tr>-->
  
    <tr>
      <th>Id</th>
      <th>Unidad de Negocio</th>
    </tr>
  </thead>
    
  
  <tbody>
    <% @areas.each do |area| %>
      <tr>
        <td><%= link_to area.id, area_path(area) %></td>
        <td><%= area.name %></td>
        <td>
          <%= link_to t('.edit', :default => 'Editar'),
                      edit_area_path(area), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => 'Eliminar'),
                      area_path(area),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Estás seguro?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%#= link_to t('.new', :default => t("helpers.links.new")),
            new_area_path,
            :class => 'btn btn-primary' %>

<%= link_to "Nueva",
            new_area_path, 
            :class => 'btn btn-primary' %>
            

app/views/areas/new.html.erb
<h1>Nueva Unidad de Negocio</h1>

<%= render 'form' %>


<%#- model_class = Area -%>
<!--<div class="page-header">
  <h1><%#=t '.title', :default => [:'helpers.titles.new', 'Agregar %{model}'], :model => 'Unidad de Negocio' %></h1>
</div>-->
<%#= render :partial => 'form' %>

app/views/areas/show.html.erb
<%- model_class = Area -%>
<div class="page-header">
  <h1>Editar Unidad de Negocio</h1>
</div>

<dl class="dl-horizontal">
  <dt><strong>Unidad de Negocio</strong></dt>
  <dd><%= @area.name %></dd>
  <!--<dt><strong><%#= model_class.human_attribute_name(:empleado_id) %>:</strong></dt>
  <dd><%#= @area.empleado.apellidos%></dd>-->
</dl>

<div class="btn-group" role="group" aria-label="...">
  <button type="button" class="btn btn-default"><%= link_to 'Editar', edit_area_path(@area) %> </button>
  <button type="button" class="btn btn-default"><%= link_to 'Atrás', areas_path %></button>
</div>

<%#= link_to t('.back', :default => t("helpers.links.back")),
              areas_path, :class => 'btn btn-default'  %>
<%#= link_to t('.edit', :default => t("helpers.links.edit")), edit_area_path(@area), :class => 'btn btn-default' %>
<%#= link_to t('.destroy', :default => t("helpers.links.destroy")),
              area_path(@area),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>