config/routes.rb
Rails.application.routes.draw do

  resources :knows

  resources :comentarios

  resources :subcategorias

  resources :categorias
  
  get 'tickets/abiertas' => 'tickets#abiertas'
  post 'tickets/asignar' => 'tickets#asignar'
  resources :tickets

  resources :subcategoria

  resources :categoria

  resources :usuarios

  resources :empleados

  resources :areas

  resources :empresas

  resources :roles
  
  

   root 'usuarios#login'

  
  match 'auth/:provider/callback', to: 'sessions#create', :via => [:get, :post]
  match 'auth/failure', to: redirect('/'), :via => [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', :via => [:get, :post]
end

app/models/area.rb
class Area < ActiveRecord::Base
  belongs_to :empresa
  has_many :categoria
  has_many :empleados
  has_many :ticket
  has_many :know
end

app/models/categoria.rb
class Categoria < ActiveRecord::Base
  belongs_to :area
  has_many :subcategoria
  has_many :ticket
  has_many :know
end

app/models/comentario.rb
class Comentario < ActiveRecord::Base
  belongs_to :ticket
  belongs_to :empleado
  belongs_to :usuario
end

app/models/empleado.rb
class Empleado < ActiveRecord::Base
  belongs_to :empresa
  belongs_to :area
  belongs_to :role
  has_many :comentario
end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
	has_many :area
	has_many :usuario
	has_many :empleado
	has_many :ticket
end

app/models/know.rb
class Know < ActiveRecord::Base
  belongs_to :area
  belongs_to :categoria
  belongs_to :subcategoria
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_many :empleado
	has_many :usuario
end

app/models/subcategoria.rb
class Subcategoria < ActiveRecord::Base
  belongs_to :categoria
  has_many :ticket
  has_many :know
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  has_many :comentario
  accepts_nested_attributes_for :comentario, allow_destroy: true
    
  belongs_to :empresa
  belongs_to :usuario
  belongs_to :empleado
  belongs_to :categoria
  belongs_to :subcategoria
  belongs_to :area
  
  
end

app/models/user.rb
class User < ActiveRecord::Base
    def self.from_omniauth(auth)
      where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.name = auth.info.name
        user.oauth_token = auth.credentials.token
        user.oauth_expires_at = Time.at(auth.credentials.expires_at)
        user.save!
      end
    end
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  belongs_to :empresa
  belongs_to :role
  has_many :ticket
  has_many :comentario
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: [:show, :edit, :update, :destroy]

  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all
    @menu = "menu2"
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
    @menu = "menu2"
  end

  # GET /roles/new
  def new
    @role = Role.new
    @menu = "menu2"
  end

  # GET /roles/1/edit
  def edit
    @menu = "menu2"
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Rol creado satisfactoriamente' }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: 'Rol actualizado satisfactoriamente' }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: 'Rol eliminado satisfactoriamente' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_params
      params.require(:role).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/categoria_helper.rb
module CategoriaHelper
end

app/helpers/categorias_helper.rb
module CategoriasHelper
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/helpers/empleados_helper.rb
module EmpleadosHelper
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/helpers/knows_helper.rb
module KnowsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
    
    def estado(id)
        case id
        when 1
            "Abierto"
        when 2
            "En proceso"
        when 3
            "Atendido"
        else
            "Error"
        end
    end
    
    def prioridad(id)
        case id
        when 1
            "Baja"
        when 2
            "Normal"
        when 3
            "Alta"
        else
            ""
        end
    end
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/roles/_form.html.erb
<%= simple_form_for @role, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="form-group">
  <%= f.input :name, :label => "Nombre" %>
  <%= error_span(@role[:name]) %>

  </div>

  <%= f.submit 'Grabar', :class => 'btn btn-sm btn-primary' %>
  <%= link_to t('.cancel', :default => "Cancelar"),
                roles_path, :class => 'btn btn-default' %>
<% end %>

app/views/roles/edit.html.erb
<%- model_class = Role -%>
<div class="page-header">
  <h1>Editar Rol</h1>
</div>
<%= render :partial => 'form' %>

app/views/roles/index.html.erb
<%= notice %>
<%- model_class = Role -%>
<div class="page-header">
  <h1>Roles</h1>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Código</th>
      <th>Nombre</th>
      <th><%=t '.actions', :default => "Acción" %></th>
    </tr>
  </thead>
  
  <tbody>
    <% @roles.each do |role| %>
      <tr>
        <td><%= link_to role.id, role_path(role) %></td>
        <td><%= role.name %></td>
        <td>
          <div class="btn-group">
          <%= link_to t('.edit', :default => "Editar"),
                      edit_role_path(role), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => "Eliminar"),
                      role_path(role),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Esta seguro de eliminar?')) },
                      :class => 'btn btn-xs btn-danger' %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => "Nuevo"),
            new_role_path,
            :class => 'btn btn-primary' %>

app/views/roles/new.html.erb
<%- model_class = Role -%>
<div class="page-header">
  <h1>Nuevo Rol</h1>
</div>
<%= render :partial => 'form' %>

app/views/roles/show.html.erb
<%- model_class = Role -%>
<div class="page-header">
  <h1>Roles</h1>
</div>

<dl class="dl-horizontal">
  <dt>Nombre</dt>
  <dd><%= @role.name %></dd>
</dl>

<%= link_to t('.back', :default => "Regresar"),
              roles_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => "Editar"),
              edit_role_path(@role), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => "Eliminar"),
              role_path(@role),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Esta seguro de eliminar?')) },
              :class => 'btn btn-danger' %>